# Generated by Django 4.2.11 on 2026-02-04 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order_index', 'created_at'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
        migrations.AddField(
            model_name='course',
            name='access_type',
            field=models.CharField(choices=[('lifetime', 'Пожизненный доступ'), ('monthly', 'Месячная подписка'), ('yearly', 'Годовая подписка')], default='lifetime', max_length=50, verbose_name='Тип доступа'),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/banners/', verbose_name='Баннер'),
        ),
        migrations.AddField(
            model_name='course',
            name='benefits',
            field=models.JSONField(blank=True, default=list, verbose_name='Преимущества'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=False, verbose_name='Сертификат прохождения'),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='course',
            name='reviews_count',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_free_preview',
            field=models.BooleanField(default=False, verbose_name='Бесплатный превью'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='Порядковый индекс'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='preview_duration_seconds',
            field=models.IntegerField(default=120, verbose_name='Длительность превью (сек)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resources',
            field=models.JSONField(blank=True, default=list, verbose_name='Файлы и ресурсы'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_content',
            field=models.TextField(blank=True, verbose_name='Текстовое описание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='timestamps',
            field=models.JSONField(blank=True, default=list, verbose_name='Таймкоды'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='last_position_seconds',
            field=models.IntegerField(default=0, verbose_name='Последняя позиция (сек)'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.IntegerField(default=0, verbose_name='Длительность (часы)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('pro', 'Pro')], default='beginner', max_length=50, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.IntegerField(default=0, verbose_name='Длительность (минуты)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='URL видео'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='watch_time_seconds',
            field=models.IntegerField(default=0, verbose_name='Время просмотра (сек)'),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Рейтинг')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
