# Generated by Django 4.2.11 on 2026-02-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_options_remove_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Видео файл'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_format',
            field=models.CharField(choices=[('16:9', 'Горизонтальное (16:9)'), ('9:16', 'Вертикальное (9:16)'), ('1:1', 'Квадратное (1:1)')], default='16:9', max_length=10, verbose_name='Формат видео'),
        ),
    ]
