# Generated by Django 4.2.11 on 2026-02-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_video_file_lesson_video_format'),
    ]

    operations = [
    ]
